name: Unify Repositories

on:
    workflow_dispatch:
    schedule:
      - cron: '0 0 * * 1'

jobs:
  unify:
    runs-on: windows-2019

    steps:
    - name: Check out main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Copy script to workspace
      run: |
        mkdir -p scripts
        cp ./unify.ps1 /tmp/unify.ps1

    - name: Check out sync branch
      uses: actions/checkout@v4
      with:
        ref: sync

    - name: Run unify.ps1
      run: |
        ls -a
        pwsh -ExecutionPolicy Bypass /tmp/unify.ps1
      shell: pwsh
    
    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git add .
        git commit -m "UPDATE: sync upstream"
        git push origin sync
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
